name: automated test
on: workflow_dispatch
jobs:
    test_code:
      runs-on: ubuntu-latest
      steps:
        - name: get code
          uses: actions/checkout@v3
        - name: get python
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"
        - name: Install packages
          run: pip install -r requirements.txt
        - name: running test
          run: python test.py
